#!/usr/bin/env python3
"""Acquire only the named collections from an explicitly pinned public mirror.
The mirror is a source witness, not an official publisher or an authenticity claim.
The operator's full-text authorization is recorded separately.
"""
from concurrent.futures import ThreadPoolExecutor, as_completed
import hashlib
import json
from pathlib import Path
import re
import subprocess
from urllib.parse import quote
import fitz
import archive_corpus as a

REPO='M0rtzz/Selected-Works-of-MaoTseTung'
COMMIT='4cc981c232e1ffe8fe2974e125c00af8376829ca'
TREES={
 '毛泽东年谱':'b9507946aa4ef157b881cfd6467f9f6090e1899c',
 '建国以来毛泽东文稿':'86a312ead8c794de0cd2143b702e525eb683abb2',
 '毛泽东选集':'8157eb5a7d487c05caaf646befef4bda75911beb'
}

def discover(client):
    records=[]; discoveries=[]
    for folder,tree_sha in TREES.items():
        url=f'https://api.github.com/repos/{REPO}/git/trees/{tree_sha}?recursive=1'
        raw,_=client.request(url)
        tree=json.loads(raw)
        if tree.get('truncated'): raise ValueError('Incomplete mirror tree')
        discoveries.append({'folder':folder,'tree':tree,'query_url':url,'retrieved_at':a.now(),'raw_sha256':a.digest(raw),'source_commit':COMMIT})
        for e in tree['tree']:
            path=e['path']
            if e['type']!='blob' or not path.endswith('.pdf'): continue
            edition=volume=None
            if folder=='毛泽东年谱':
                if path.startswith('2023年版/'):
                    m=re.search(r'第(\d+)卷',path)
                    if not m: continue
                    edition,volume='nianpu-2023-9',int(m.group(1))
                elif path.startswith('1993年版/'):
                    m=re.search(r'_([上中下])卷',path)
                    if not m: continue
                    edition,volume='nianpu-pre1949-3',{'上':1,'中':2,'下':3}[m.group(1)]
                else: continue
            elif folder=='建国以来毛泽东文稿':
                m=re.search(r'第(\d+)册',path)
                if not m: continue
                edition,volume='wengao-2023-20',int(m.group(1))
            elif folder=='毛泽东选集':
                if path!='毛泽东选集.pdf': continue
                edition,volume='maoxuan-mirror-combined-unverified',None
            fullpath=folder+'/'+path
            url=f'https://raw.githubusercontent.com/{REPO}/{COMMIT}/'+quote(fullpath,safe='/')
            records.append({'url':url,'title':Path(path).stem,'kind':'pdf_link','source_ids':['GH-M0RTZZ-PINNED'],
                            'catalogue_entry_ids':[],
                            'edition_refs':[{'edition_id':edition,'volume':volume,'basis':'mirror_folder_and_filename_pending_book_imprint_check'}],
                            'mirror_repository':REPO,'mirror_commit':COMMIT,'mirror_path':fullpath,
                            'mirror_git_blob_sha1':e['sha'],'mirror_expected_bytes':e['size'],
                            'edition_verification_status':'filename_label_not_yet_imprint_verified'})
    a.write('reports/mirror-book-discovery.json',discoveries)
    a.lines('archive/index/mirror-targets.jsonl',records)
    return records


def verify_source_identity(r):
    if r['status']!='preserved': return r
    raw=a.raw_bytes(r)
    actual=hashlib.sha1(b'blob '+str(len(raw)).encode()+b'\0'+raw).hexdigest()
    if len(raw)!=r['mirror_expected_bytes'] or actual!=r['mirror_git_blob_sha1']:
        r.update(status='failed',error='mirror length or original Git blob hash mismatch')
    else:
        r['mirror_git_blob_verified']=True
        document=fitz.open(stream=raw,filetype='pdf')
        extracts=[]
        paths=[]
        for n in range(min(6,len(document))):
            page=document[n]
            extracts.append({'pdf_page':n+1,'text':page.get_text('text')})
            path=a.BASE/'edition-checks'/r['id']/f'page-{n+1:02d}.png'
            path.parent.mkdir(parents=True,exist_ok=True)
            page.get_pixmap(matrix=fitz.Matrix(0.8,0.8)).save(path)
            paths.append(a.rel(path))
        r['imprint_candidate_text']=extracts
        r['imprint_candidate_images']=paths
        r['edition_verification_status']='source_bytes_verified_imprint_images_available_for_review'
        document.close()
    a.write(a.record_path(r['url']),r)
    return r


def checkpoint(message):
    # Only paths generated by this acquisition are staged. Never rewrite history.
    subprocess.run(['git','add','archive','reports/mirror-book-discovery.json'],check=True)
    if subprocess.run(['git','diff','--cached','--quiet']).returncode==0: return
    subprocess.run(['git','commit','-m',message],check=True)
    for _ in range(3):
        subprocess.run(['git','pull','--rebase','origin','main'],check=True)
        if subprocess.run(['git','push','origin','HEAD:main']).returncode==0: return
    raise RuntimeError('Concurrent remote updates prevented a non-forced push')


def main():
    a.HOSTS.update({'api.github.com','raw.githubusercontent.com'})
    original_safe=a.safe
    def restricted(url):
        from urllib.parse import urlsplit
        p=urlsplit(url)
        if p.hostname=='raw.githubusercontent.com':
            return p.scheme=='https' and p.path.startswith('/'+REPO+'/'+COMMIT+'/') and not p.username and not p.password
        if p.hostname=='api.github.com':
            return p.scheme=='https' and p.path.startswith('/repos/'+REPO+'/git/trees/') and not p.username and not p.password
        return original_safe(url)
    a.safe=restricted
    client=a.Client(0.3)
    targets=discover(client)
    # Public raw Github paths only, already scoped to a fixed tree/commit.
    # No auth token is sent to public source hosts.
    for i in range(0,len(targets),4):
        with ThreadPoolExecutor(max_workers=3) as pool:
            fs=[pool.submit(a.acquire,r,client) for r in targets[i:i+4]]
            for future in as_completed(fs):
                r=verify_source_identity(future.result())
                print(r['title'],r['status'],r.get('pdf_pages'),r.get('text_layer_status'),flush=True)
        checkpoint(f'data: preserve pinned mirror books batch {i//4+1}, including exact original Git blob verification')
    # Shared aggregate indexes are rebuilt only by final integration, avoiding
    # collisions with concurrent main-source acquisition.
    a.write('reports/mirror-book-results.json',{
        'generated_at':a.now(),'source_repository':REPO,'source_commit':COMMIT,
        'target_count':len(targets),'results':[a.load(a.record_path(r['url'])) for r in targets]})


if __name__=='__main__': main()
