#!/usr/bin/env python3
"""Resume preservation without losing completed source files at a final commit.
Only this corpus's generated archive/reports/exports are staged. No force-push.
"""
from concurrent.futures import ThreadPoolExecutor,as_completed
import json
import subprocess
import time
from pathlib import Path
from urllib.parse import urlsplit
import archive_corpus as a


def checkpoint(message):
    subprocess.run(['git','add','archive','reports','exports'],check=True)
    if subprocess.run(['git','diff','--cached','--quiet']).returncode==0: return
    subprocess.run(['git','commit','-q','-m',message],check=True)
    for attempt in range(4):
        # The only changes generated by acquisition are now committed, so a
        # concurrent research update can be rebased without discarding files.
        subprocess.run(['git','pull','--rebase','origin','main'],check=True)
        result=subprocess.run(['git','push','origin','HEAD:main'])
        if result.returncode==0: return
        time.sleep(2+attempt)
    raise RuntimeError('Could not publish with a normal non-forced push')


def main():
    if not (a.ROOT/a.GRANT).exists(): raise RuntimeError('Missing operator authorization')
    selected=[r for r in a.targets().values() if r['kind']!='pdf_link' and not urlsplit(r['url']).path.lower().endswith('.chm')]
    # MIA body texts first. Auxiliary material with long failures cannot block
    # persistence of already obtained requested source files.
    selected.sort(key=lambda r:(not urlsplit(r['url']).hostname.endswith('marxists.org'),r['url']))
    client=a.Client(0.3); client.prepare([r['url'] for r in selected])
    for offset in range(0,len(selected),60):
        batch=selected[offset:offset+60]
        with ThreadPoolExecutor(max_workers=5) as pool:
            fs=[pool.submit(a.acquire,r,client) for r in batch]
            results=[future.result() for future in as_completed(fs)]
        a.write('reports/html-resume-progress.json',{
            'generated_at':a.now(),'targets':len(selected),'processed':min(offset+60,len(selected)),
            'last_batch_preserved':sum(r['status']=='preserved' for r in results),
            'last_batch_failures':[{'url':r['url'],'error':r.get('error')} for r in results if r['status']!='preserved']})
        checkpoint(f'data: preserve full HTML source bodies checkpoint {offset//60+1}')
        print('Committed HTML checkpoint',min(offset+60,len(selected)),len(selected),flush=True)
    a.build_index()
    a.verify()
    checkpoint('audit: verify retained HTML source bytes and complete exact-URL mappings')


if __name__=='__main__': main()
